### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by CTMendoza** [CTMendoza/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [ ]  populate the image of the car onto the web page
- [ ] make sure the car is set on the top left corner of the web page
- [ ] change background of the webpage to green
